# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempe', '0004_aldeia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdistrict',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistrict', to='tempe.District'),
        ),
    ]
