# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempe', '0004_aldeia_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='aldeia',
            field=models.ManyToManyField(blank=True, null=True, to='tempe.Aldeia'),
        ),
    ]
