# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempe', '0005_auto_20160623_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('aldeia', models.ManyToManyField(related_name='tourist', to='tempe.Aldeia')),
            ],
        ),
    ]
