# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempe', '0005_auto_20160622_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='aldeia',
            field=models.ManyToManyField(to='tempe.Aldeia'),
        ),
    ]
