# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempe', '0006_tourist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='aldeia',
            field=models.ManyToManyField(related_name='tourists', to='tempe.Aldeia'),
        ),
    ]
