# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempe', '0006_auto_20160623_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aldeia',
            name='suco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldeias', to='tempe.Suco'),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='tempe.District'),
        ),
        migrations.AlterField(
            model_name='suco',
            name='subdistrict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucos', to='tempe.SubDistrict'),
        ),
    ]
