# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempe', '0006_auto_20160623_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='aldeias',
            new_name='aldeia',
        ),
    ]
