# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempe', '0007_auto_20160623_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist',
            old_name='aldeia',
            new_name='aldeias',
        ),
    ]
